### ISSUE TITLE
zipkin store uses v1 url

### ISSUE THREAD

**Issue by adriancole** [ExpediaDotCom/haystack-ui#396]
https://github.com/ExpediaDotCom/haystack-ui#haystack-ui-as-drop-in-replacement-for-zipkin-ui suggests v1 endpoint. While this is ok actually the UI currently consumes v2 data, which is incidentally pretty similar to your data format I think https://zipkin.io/zipkin-api/#/default/get_traces

**Comment by adriancole** [comment]
cheers.. by the way I think if I were you I wouldn't do that as the
maintenance overhead seems not useful. v2 endpoints have existed a long
time (maybe 2 years now) and the server is easy to upgrade. remember we are
talking about the read side.

**Comment by adriancole** [comment]
by read side I mean both v1 and v2 write endpoints are mounted on the
server and will be for the foreseeable future.

**Comment by adriancole** [comment]
PS I made a mistake.. we actually only support *write* apis for v1 and v2. @drolando noticed this.

Maybe there's a way we can extract a conversion library or worst case copy/paste it here until the internals can be redone for v2 format?

https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/js/spanConverter.js

ex here's logic we use as we couldn't immediately refactor internals, so we convert the v2 api to v1 data:
```javascript
      const v1Trace = raw.map(SPAN_V1.convert);
      const mergedTrace = SPAN_V1.mergeById(v1Trace);
      const clockSkewCorrectedTrace = correctForClockSkew(mergedTrace);
```
https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/js/component_data/trace.js#L23

cc also @zeagord

**Comment by adriancole** [comment]
ps I will timebox a bit today to try the conversion approach as I was able to do it for our UI which is probably technically more gnarly :P I will report back as definitely we have a goal of folks being able to interop and use your nice things especially data pipeline in nature

**Comment by vsen** [comment]
Sure, thanks @adriancole. Simple conversion would work for now. If that doesn't work, we can look into creating a new connector.

**Comment by adriancole** [comment]
started work here. If you don't mind having a look at the approach. I'm needing to borrow some code from our UI codebase, but it is different because haystack format looks like somewhere between zipkin v1 and v2 format. This isn't a problem, just saying I'll need to port all the tests for this to work. https://github.com/ExpediaDotCom/haystack-ui/pull/400

**Comment by adriancole** [comment]
pretty far along on this.. fwiw

**Comment by vsen** [comment]
FYI. There were some gaps in trace search with zipkin backend. Working on the corresponding changes in https://github.com/ExpediaDotCom/haystack-ui/tree/zipkin-run-suite branch and trying to create a test/run suite with Zipkin backend.

**Comment by vsen** [comment]
FYI, this PR will fill in some gaps in traces search with Zipkin backend - https://github.com/ExpediaDotCom/haystack-ui/pull/404. Zipkin test/run suite is still pending though.

**Comment by bulicekj** [comment]
closing as this is (long) fixed
