### ISSUE TITLE
Span Detail View Improvements

### ISSUE THREAD

**Issue by bulicekj** [ExpediaDotCom/haystack-ui#427]
When viewing a detailed view of a [merged span](https://github.com/ExpediaDotCom/haystack-traces/blob/master/reader/src/main/scala/com/expedia/www/haystack/trace/reader/readers/utils/SpanMerger.scala), it's not clear what you're actually looking at. Currently, you see a view of merged tags, merged logs, and the (server) raw span. This should be improved so the user knows more clearly what they are viewing.

**Comment by adriancole** [comment]
we are currently restructuring zipkin ui to retain this stuff as well. this
is in effort to be v2 native wrt data format inside our ui.

some thoughts of note: qualifying the nodes in your internal representation
of tree can differentiate client from server side even if they share the
same ID.
