### ISSUE TITLE
dead already

### ISSUE THREAD

**Issue by adriancole** [ExpediaDotCom/haystack-ui#447]
fun title in malaysian slang. The zipkin quickstart dies recently. Mind looking into it?

![screen shot 2018-12-13 at 4 35 02 pm](https://user-images.githubusercontent.com/64215/49925867-1bb3a200-fef5-11e8-8c0c-56629e4b2e5c.png)

**Comment by bulicekj** [comment]
Closing, as I'm not able to reproduce. This was probably fixed some time ago.
