### ISSUE TITLE
Clicks on bubbles in Service Performance graph sometimes fail

### ISSUE THREAD

**Issue by JordanJLopez** [ExpediaDotCom/haystack-ui#449]
Occasionally, clicking on certain (usually smaller) service bubbles in the Service Performance graph does not trigger a redirect. Repeated clicks (sometimes as many as five or six) are needed to actually get the desired effect of going to the service's page.

We're currently running the following versions:
- **1.0.3** of haystack-ui (we've seen this in 1.0.1 as well)
- **1.0.5** of haystack-traces (we've seen this in 1.0.3 as well)
- **1.0.2** of haystack-trends (we've seen this in 1.0.1 as well)

**Comment by shreyaa-sharma** [comment]
Tagging our UI specialists @bulicekj @absrivastava.

**Comment by bulicekj** [comment]
@JordanJLopez are you still experiencing this? Is there any stack trace in the console? I'm unable to reproduce

**Comment by shreyaa-sharma** [comment]
Closing this issue as we have not been able to reproduce it and not heard back.
