### ISSUE TITLE
Support for additional comparisons beyond equality in Universal Search

### ISSUE THREAD

**Issue by JordanJLopez** [ExpediaDotCom/haystack-ui#465]
For at least one of the tags that we use, the value of the tag is a numerical value based on a sliding scale rather than a distinct value. It would be great for Universal Search to support the ability to search on all values greater than a given value, or less than a given value, or between two different values.

For example, our tag is something like `quality-rating` with a scale from -10 to 10, where > 0 is better, and < 0 is worse. Currently, if I wanted to get all the bad ones, I'd have to make 10 different searches for quality-rating = -1, quality-rating = -2, etc.

**Comment by bulicekj** [comment]
As mentioned in our [Gitter channel](https://gitter.im/expedia-haystack/Lobby), this is a feature that's coming in Q1. Will leave this issue open as a reference for incoming PRs.

**Comment by bulicekj** [comment]
Added as of #478
