### ISSUE TITLE
Trends, Alerts, and Service Graph tabs disappear

### ISSUE THREAD

**Issue by desumera** [ExpediaDotCom/haystack-ui#472]
Steps to reproduce:

1. Navigate to the traces of a service, like `https://<haystackUrl>/search?time.preset=1h&serviceName=<serviceName>&tabId=traces`
2. Click a bar in the timeline: 
![image](https://user-images.githubusercontent.com/612105/53049788-728da880-345d-11e9-8383-e108caa6e811.png)

Expected result:
The Trends page opens for the correct time window, with all UI components rendered properly

Actual result:
The Trends page opens, but the tab options are gone (see below)
![image](https://user-images.githubusercontent.com/612105/53049860-9f41c000-345d-11e9-95e9-eba11a632649.png)

**Comment by bulicekj** [comment]
Fixed as of #478
