### ISSUE TITLE
Universal Search can not search for tags with periods in their names in 1.0.4

### ISSUE THREAD

**Issue by JordanJLopez** [ExpediaDotCom/haystack-ui#477]
We recently tried moving to a more recent version of Haystack UI that heavily featured Universal Search, and discovered that there is an issue with searching for certain tags with periods in the name, such as `http.method`

![dot-name-1](https://user-images.githubusercontent.com/8593393/55185144-bb720480-5161-11e9-83bd-6ca3691c08b7.png)

![dot-name-2](https://user-images.githubusercontent.com/8593393/55185154-bf058b80-5161-11e9-8155-eafb491a5e7e.png)

![dot-name-3](https://user-images.githubusercontent.com/8593393/55185159-c331a900-5161-11e9-85b4-c9a39bd4b42a.png)

**Comment by bulicekj** [comment]
Fixed as of #478
