### ISSUE TITLE
how to run without nodejs?

### ISSUE THREAD

**Issue by zhanglei-1987** [ExpediaDotCom/haystack-ui#533]
good ui for zipkin, i  want  nest  to my application, how to run without nodejs?

**Comment by bulicekj** [comment]
Hi, this is a nodejs app, and thus requires node to run it. You are welcome to fork and try bringing in the build with whatever other backend you are planning on using, but we only support node. If you want to use Haystack with Zipkin, I suggest you check out https://github.com/ExpediaDotCom/haystack-docker where we have instructions on spinning up a haystack cluster while pushing us zipkin spans
