### ISSUE TITLE
Including X-HAYSTACK-INFRASTRUCTURE-PROVIDER	onto search bar 

### ISSUE THREAD

**Issue by yyemane206** [ExpediaDotCom/haystack-ui#534]
Including this in the search will allow my team to search for service failures by environment. If its in AWS or DC.

**Comment by absrivastava** [comment]
@yyemane206 You can whitelist keys according to your search needs and it will appear in suggestions. 

https://expediadotcom.github.io/haystack/docs/about/getting_started.html#how-to-whitelist-a-key-for-search
