### ISSUE TITLE
npm install error with nodejs 12.13.1

### ISSUE THREAD

**Issue by zhanglei-1987** [ExpediaDotCom/haystack-ui#537]
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/haystack-ui-1.1.8/node_modules/canvas/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, stat '/root/haystack-ui-1.1.8/node_modules/canvas/.node-gyp/12.13.1'
gyp ERR! System Linux 3.10.0-1062.7.1.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/haystack-ui-1.1.8/node_modules/canvas
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-06T02_23_16_494Z-debug.log

**Comment by bulicekj** [comment]
Hi, can you share what your OS is and whether you were able to successfully install the dependencies found [here](https://github.com/ExpediaDotCom/haystack-ui#testing)? There may be additional steps requred to install node-gyp [here as well](https://github.com/nodejs/node-gyp)

**Comment by bulicekj** [comment]
I can guarantee this is not a node issue, as I am able to install, build, and run on v12.13.1
